[package]
name = "book_catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
chrono = "0.4.22"
regex = "1.6.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde-xml-rs = "0.6.0"